### ISSUE TITLE
[프론트엔드]  Signup 컴포넌트

### ISSUE THREAD

**Issue by kaehehehe** [codestates/pink-devsaurus#11]
### ISSUE
* Group:  `client`
* Type: `feat`
* Detail: Signup 컴포넌트 작성
 
### TODO
- [ ]  공룡 이미지를 클릭 시 main 페이지에 이동할 수 있게 활성화
- [ ]  입력한 usernama혹은 email이 이미 db에 존재하는 경우, 에러 표시
- [ ]  password가 짧거나 숫자, 특수문자가 포함되어 있지 않으면 에러 표시
- [ ]  password, confrim password가 일치하지 않으면 에러 표시
 
### Labels
* Estimated time: `3h`
* Group : `client`
* Urgency: `Middle`
