### ISSUE TITLE
[프론트엔드] Write 컴포넌트 작성

### ISSUE THREAD

**Issue by exxocism** [codestates/pink-devsaurus#12]
### ISSUE
* Group: `client`
* Type: `feat`
* Detail: 외부 API를 이용한 텍스트 에디터 글쓰기 컴포넌트 작성
 
### TODO
- [x]  Markdown 에디터 선정 및 적용
- [x]  React styled 적용
- [ ]  컴포넌트 간 작동여부 테스트
 
### Labels
* Estimated time: `3h`
* Group : `client`
* Urgency: `Middle`
