### ISSUE TITLE
[프론트엔드] Contents 컴포넌트 작성

### ISSUE THREAD

**Issue by exxocism** [codestates/pink-devsaurus#15]
### ISSUE
* Group: `client`
* Type: `feat`
* Detail: 게시물의 목록을 보여주는 컴포넌트 작성
 
### TODO
- [x]  Contents 레이아웃 및 UI 구성
- [x]  Content 레이아웃 및 UI 구성
- [x]  Main 페이지 컴포넌트 생성
- [x]  props를 이용해 Contents, Content View 렌더
- [x]  props로 사용할 Content 목록 데이터 통신
- [x]  페이지네이션 레이아웃 및 UI
- [x]  페이지네이션 데이터 통신
 
### Labels
* Estimated time: `3h`
* Group : `client`
* Urgency: `Middle`
