### ISSUE TITLE
[프론트엔드]  Answer 컴포넌트 작성

### ISSUE THREAD

**Issue by exxocism** [codestates/pink-devsaurus#17]
### ISSUE
* Group: `client`
* Type: `feat`
* Detail: 답변글의 목록을 보여주는 컴포넌트 작성
 
### TODO
- [x]  Markdown 컴포넌트 연동
- [x]  수정 및 답변체크 기능 확인
- [ ]  백엔드및 타 컴포넌트와의 연동 체크
 
### Labels
* Estimated time: `3h`
* Group : `client`
* Urgency: `Middle`
