### ISSUE TITLE
[프론트엔드] Header, Footer 컴포넌트

### ISSUE THREAD

**Issue by krim45** [codestates/pink-devsaurus#3]
### ISSUE
* Group:  `client`
* Type: `feat`
* Detail: Header, Footer 컴포넌트 작성
 
### TODO
* [x]  Footer 컴포넌트 작성
* [x]  로그인, 회원가입 버튼 / 프로필 이미지 조건부 랜더링
* [x]  버튼 UI
* [x]  드롭다운메뉴 구현
* [x]  서치바 컴포넌트, 드롭다운 컴포넌트 분리
* [x]  메뉴 버튼 레이아웃
 
### Labels
* Estimated time: `E: 3h`
* Group : `client`
* Urgency: `Middle`
