### ISSUE TITLE
[프론트엔드] 프로젝트 초기 환경 설정

### ISSUE THREAD

**Issue by exxocism** [codestates/pink-devsaurus#4]
### ISSUE
* Group: `client`
* Type: `feat`
* Detail: 초기 환경 설정
 
### TODO
- [x]  node, npm, mysql 버전 통일
- [x]  create-reac-app을 통한 사용환경 구성
- [x]  package-lock.json을 통한 버전 통일 (npm ci)
 
### Labels
* Estimated time: `3h`
* Group : `client`
* Urgency: `Middle`
