### ISSUE TITLE
[사전준비단계] 배포 

### ISSUE THREAD

**Issue by AbyulStudy** [codestates/pink-devsaurus#5]
### ISSUE
* Group:  `server`
* Type: `배포서버 구축`
* Detail: 
 
### TODO
* [x]  EC2 / RDS 구축
* [x]  HTTPS ( SSL / TTL ) 통신 구축
- * [x]  User -> ELB
- * [x]  ELB -> EC2
- * [x]  EC2 -> RDS
- * [ ]  User -> CDN
- * [ ]  CDN -> Git Pages
* [x]  Domain name 설정
 
### Labels
* Estimated time: `3h`
* Group :  `server`
* Urgency: `High`
