### ISSUE TITLE
[프론트엔드]  Mystatus 컴포넌트

### ISSUE THREAD

**Issue by kaehehehe** [codestates/pink-devsaurus#55]
### ISSUE
* Group:  `client`
* Type: `feat`
* Detail: fix actions from client redux
 
### TODO
- [ ]  유저 정보가 표시되어야 한다.
- [ ]  내 질문 보기 버튼 활성화
- [ ]  내 댓글 보기 버튼 활성화
 
### Estimated time
> Pick one

### Labels
* Estimated time: `E: 3h`
* Group : `client`
* Urgency: `Middle`
