### ISSUE TITLE
[프론트엔드] Loading 컴포넌트 작성

### ISSUE THREAD

**Issue by exxocism** [codestates/pink-devsaurus#6]
### ISSUE
* Group: `client`
* Type: `feat`
* Detail: 로딩 컴포넌트 작성
 
### TODO
- [x]  모달창 디자인 및 공룡사진 삽입
- [x]  애니메이션 CSS 적용
- [ ]  사용하고자 하는 컴포넌트에서 조건부 렌더링
 
### Labels
* Estimated time: `3h`
* Group : `client`
* Urgency: `Middle`
