### ISSUE TITLE
[프론트엔드] Read 페이지 작성

### ISSUE THREAD

**Issue by exxocism** [codestates/pink-devsaurus#68]
### ISSUE
* Group:  `client`
* Type: `SR기획`
* Detail: Read 페이지 작성
 
### TODO
- [x]  Question 컴포넌트 연동
- [x]  Answer 컴포넌트 연동
- [x]  Write 컴포넌트 연동
 
### Estimated time
> Pick one

### Labels
* Estimated time: `E: 1h`
* Group : `client`
* Urgency:  `Middle`
