### ISSUE TITLE
[프론트엔드]  Login 컴포넌트

### ISSUE THREAD

**Issue by kaehehehe** [codestates/pink-devsaurus#7]
### ISSUE
* Group:  `client`
* Type: `feat`
* Detail: Login component 작성
 
### TODO
- [ ]  공룡 이미지를 클릭 시 main 페이지에 이동할 수 있게 활성화
- [ ]  올바른 email 주소, password를 입력하면 로그인이 되고 main 페이지에 이동
- [ ]  입력한 email 주소와 password가 일치하지 않으면 에러 메시지를 표시
 
### Labels
* Estimated time: `3h`
* Group : `client`
* Urgency: `Middle`
