### ISSUE TITLE
[프론트엔드] Sidebar CSS 수정, Contents 목록 개수, Footer CSS 수정

### ISSUE THREAD

**Issue by krim45** [codestates/pink-devsaurus#70]
### ISSUE
* Group:  `client`
* Type: `art`
* Detail: CSS 변경
 
### TODO
- [x] Sidebar 카테고리 이미지 제거
- [x] Sidebar CSS 수정
- [x] Contents 목록 개수 10개로 변경
- [x] Footer CSS 수정
- [x] CSS 단위기준 변경 rem -> vmax
 
### Labels
* Estimated time: `E: 1h`
* Group : `client`
* Urgency: `Middle`
